@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Person(user, "Pessoa Desenvolvedora de SW/QA/Power User/Executora ou Gestora da Infra Corporativa/Parte de ambiente corporativo", "Qualquer pessoa que deseje executar e/ou compartilhar Fórmulas para fins de automação ou outros em sua máquina pessoal e/ou corporativa".)

System_Ext(shells, "Shells do Windows/MacOS/Linux (CMD/PowerShell/Bash/Zsh)", "Intermediam interações com o Ritchie CLI, SDKs/Runtimes e/ou Docker, e executam Fórmulas escritas em linguagem shell".)
System_Ext(sdks, "SDKs/runtimes de linguagens de programação diversas", "Compilam e executam Fórmulas").
System_Ext(remote_repos, "APIs GitHub/Gitlab/Bitbucket", "Provêem acesso a repositórios de Fórmulas").
System_Ext(filesystem, "Sistema de arquivos", "Armazena Fórmulas e seus templates").

Container_Boundary(ritchie_system, "Ritchie System") {
    Container(ritchie_cli, "RitchieCLI", "CLI, motor de execução e compartilhamento de Fórmulas").
    Container(ritchie_formulas, "Fórmulas", "Código arbitrário provido pela pessoa usuária ou a comunidade").
}

Container_Boundary(docker_system, "Docker System") {
    Container(docker_engine, "Docker Engine", "Manipula contêineres").
    Container(docker_containers, "Contêineres", "Oferecem ambiente virtual com SDKs/runtimes pré-configurados para compilação e execução de Fórmulas".)
    Container(docker_sdks, "SDKs/runtimes de linguagens de programação diversas", "Compilam e executam Fórmulas").

    Rel(docker_engine, docker_containers, "Cria, inicia, manipula e para").
    Rel(docker_containers, docker_sdks, "Possuem pré-instalados e configurados OS").
    Rel(docker_sdks, ritchie_formulas, "Compilam e/ou executam", "APIs do SO|Novo processo").
}

Rel(user, shells, "Abre para invocar comandos do RitchieCLI").
Rel(shells, ritchie_cli, "Iniciam e chamam", "Shell Exec|Novo processo").
Rel(ritchie_formulas, ritchie_formulas, "Chamam", "Comando shell").
Rel(ritchie_cli, sdks, "Chama", "Comando shell").
Rel(sdks, ritchie_formulas, "Compilam e/ou executam", "APIs do SO|Novo processo").
Rel(shells, ritchie_formulas, "Executam", "Shell Exec|Novo processo").
Rel(ritchie_cli, docker_engine, "Chama", "Comando shell").
Rel(ritchie_cli, remote_repos, "Chama", "HTTPS").
Rel(ritchie_cli, filesystem, "Lê e grava em", "Golang FS APIs").

@enduml
