@startuml c1
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Person(user, "Pessoa Desenvolvedora de SW/QA/Power User/Executora ou Gestora da Infra Corporativa/Parte de ambiente corporativo", "Qualquer pessoa que deseje executar e/ou compartilhar código arbitrário para fins de automação ou outros em sua máquina pessoal e/ou corporativa")

System(ritchiecli, "RitchieCLI", "Motor de execução e compartilhamento de código arbitrário")
System_Ext(docker, "Docker").
System_Ext(shells, "Shells do Windows/MacOS/Linux (CMD/PowerShell/Bash/Zsh)")
System_Ext(sdks, "SDKs/runtimes de diversas linguagens de programação")
System_Ext(remote_repos, "Repositórios de código remotos (GitHub, Gitlab ou Bitbucket)")

Rel(user, shells, "Compila, executa e/ou interpreta comandos do RitchieCLI para executar ou compartilhar código arbitrário em/da sua máquina")
Rel(shells, ritchiecli, "Repassa comandos da pessoa usuária")
Rel(ritchiecli, shells, "Executa shells com finalidade de interagir com estas ou intermediar interações com Docker/SDKs/runtimes")
Rel(shells, sdks, "Compila, executa e/ou interpreta o código arbitrário em ambiente nativo")
Rel(shells, docker, "Delega compilação e/ou execução de código arbitrário para contêineres")
Rel(ritchiecli, remote_repos, "Importa ou exporta código arbitrário")
@enduml
