@startuml c2
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

Person(user, "SW Development Person/QA/Power User or Manager of Corporate Infrastructure/Part of the corporate environment", "Anyone who wants to run and/or share Formulas for automation or other purposes on your personal and/or corporate machine").

System_Ext(shells, "Windows/MacOS/Linux (CMD/PowerShell/Bash/Zsh) shell", "Intermediate interactions with Ritchie CLI, SDKs/Runtimes and/or Docker, and execute Formulas written in shell language").
System_Ext(sdks, "SDKs/runtimes of several programming languages", "Compile and run Formulas").
System_Ext(remote_repos, "APIs GitHub/Gitlab/Bitbucket", "Provide access to the Formulas repository").
System_Ext(filesystem, "File system", "Store formulas and their templates").

Container_Boundary(ritchie_system, "Ritchie System") {
    Container(ritchie_cli, "RitchieCLI", "CLI, execution engine and Formula sharing").
    Container(ritchie_formulas, "Formulas", "Arbitrary code provided by the user or the community").
}

Container_Boundary(docker_system, "Docker System"). {
    Container(docker_engine, "Docker Engine", "Manipulate containers").
    Container(docker_containers, "Containers", "They offer a virtual environment with pre-configured SDKs/runtimes for compilation and execution of Formulas").
    Container(docker_sdks, "SDKs/runtimes of several programming languages", "Compile and run Formulas").

    Rel(docker_engine, docker_containers, "Create, start, manipulate and stop").
    Rel(docker_containers, docker_sdks, "They have pre-installed and configured OS").
    Rel(docker_sdks, ritchie_formulas, "Compile and/or run", "APIs do SO|New process").
}

Rel(user, shells, "Abre para invocar comandos do RitchieCLI").
Rel(shells, ritchie_cli, "Start and call", "Shell Exec|New process").
Rel(ritchie_formulas, ritchie_formulas, "Call", "Shell command").
Rel(ritchie_cli, sdks, "Call", "Shell command").
Rel(sdks, ritchie_formulas, "Compile and/or run", "APIs do SO|New process").
Rel(shells, ritchie_formulas, "Run", "Shell Exec|New process").
Rel(ritchie_cli, docker_engine, "Call", "Shell command").
Rel(ritchie_cli, remote_repos, "Call", "HTTPS").
Rel(ritchie_cli, filesystem, "Read and record in", "Golang FS APIs").
@enduml
